[2025-03-27T14:26:02.904-0500] {processor.py:186} INFO - Started process (PID=1763001) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:26:02.904-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T14:26:02.905-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:26:02.905-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:26:02.907-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:26:02.907-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T14:26:02.907-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:26:02.907-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T14:26:02.908-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:26:02.913-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-03-27T14:28:24.285-0500] {processor.py:186} INFO - Started process (PID=1764274) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:28:24.286-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T14:28:24.287-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:28:24.287-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:28:24.290-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:28:24.290-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T14:28:24.290-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:28:24.290-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T14:28:24.290-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:28:24.295-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2025-03-27T14:35:37.989-0500] {processor.py:186} INFO - Started process (PID=1768477) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:35:37.989-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T14:35:37.990-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:35:37.990-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:35:37.992-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:35:37.992-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T14:35:37.992-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:35:37.992-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T14:35:37.992-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:35:37.998-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-03-27T14:37:24.338-0500] {processor.py:186} INFO - Started process (PID=1769538) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:37:24.338-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T14:37:24.339-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:37:24.339-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:37:24.341-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:37:24.341-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T14:37:24.341-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:37:24.341-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T14:37:24.341-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:37:24.346-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-03-27T14:38:31.002-0500] {processor.py:186} INFO - Started process (PID=1770523) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:38:31.002-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T14:38:31.003-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:38:31.003-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:38:31.005-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:38:31.004-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T14:38:31.005-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:38:31.005-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T14:38:31.005-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:38:31.010-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-03-27T14:39:45.414-0500] {processor.py:186} INFO - Started process (PID=1771362) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:39:45.414-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T14:39:45.416-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:39:45.415-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:39:45.417-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:39:45.417-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T14:39:45.417-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:39:45.417-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T14:39:45.418-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:39:45.423-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-03-27T14:41:07.528-0500] {processor.py:186} INFO - Started process (PID=1772153) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:41:07.529-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T14:41:07.530-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:41:07.529-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:41:07.531-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:41:07.531-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T14:41:07.531-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:41:07.531-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T14:41:07.532-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:41:07.537-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-03-27T14:42:32.894-0500] {processor.py:186} INFO - Started process (PID=1773221) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:42:32.895-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T14:42:32.896-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:42:32.895-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:42:32.897-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:42:32.897-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T14:42:32.897-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:42:32.897-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T14:42:32.897-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:42:32.903-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-03-27T14:43:59.134-0500] {processor.py:186} INFO - Started process (PID=1774272) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:43:59.135-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T14:43:59.136-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:43:59.135-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:43:59.137-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:43:59.137-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T14:43:59.137-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:43:59.137-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T14:43:59.138-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:43:59.143-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-03-27T14:45:03.434-0500] {processor.py:186} INFO - Started process (PID=1774922) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:45:03.434-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T14:45:03.435-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:45:03.435-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:45:03.437-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:45:03.436-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T14:45:03.437-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:45:03.437-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T14:45:03.437-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:45:03.442-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-03-27T14:46:41.089-0500] {processor.py:186} INFO - Started process (PID=1775856) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:46:41.089-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T14:46:41.090-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:46:41.090-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:46:41.092-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:46:41.091-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T14:46:41.092-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:46:41.092-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T14:46:41.092-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:46:41.097-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-03-27T14:47:54.272-0500] {processor.py:186} INFO - Started process (PID=1776593) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:47:54.273-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T14:47:54.274-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:47:54.273-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:47:54.275-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:47:54.275-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T14:47:54.275-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:47:54.275-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T14:47:54.276-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:47:54.281-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-03-27T14:49:13.968-0500] {processor.py:186} INFO - Started process (PID=1777236) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:49:13.969-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T14:49:13.970-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:49:13.970-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:49:13.972-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:49:13.971-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T14:49:13.972-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:49:13.972-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T14:49:13.972-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:49:13.977-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-03-27T14:50:13.091-0500] {processor.py:186} INFO - Started process (PID=1777802) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:50:13.092-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T14:50:13.093-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:50:13.092-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:50:13.094-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:50:13.094-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T14:50:13.094-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:50:13.094-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T14:50:13.095-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:50:13.100-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-03-27T14:51:18.876-0500] {processor.py:186} INFO - Started process (PID=1783305) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:51:18.876-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T14:51:18.877-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:51:18.877-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:51:18.879-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:51:18.879-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T14:51:18.879-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:51:18.879-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T14:51:18.879-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:51:18.885-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-03-27T14:52:25.922-0500] {processor.py:186} INFO - Started process (PID=1783992) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:52:25.923-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T14:52:25.924-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:52:25.923-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:52:25.925-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:52:25.925-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T14:52:25.925-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:52:25.925-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T14:52:25.925-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:52:25.931-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-03-27T14:53:36.900-0500] {processor.py:186} INFO - Started process (PID=1784702) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:53:36.900-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T14:53:36.901-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:53:36.901-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:53:36.903-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:53:36.903-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T14:53:36.903-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:53:36.903-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T14:53:36.903-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:53:36.909-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-03-27T14:54:43.619-0500] {processor.py:186} INFO - Started process (PID=1785406) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:54:43.620-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T14:54:43.621-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:54:43.621-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:54:43.623-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:54:43.622-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T14:54:43.623-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:54:43.623-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T14:54:43.623-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:54:43.628-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-03-27T14:55:48.751-0500] {processor.py:186} INFO - Started process (PID=1786116) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:55:48.751-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T14:55:48.752-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:55:48.752-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:55:48.754-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:55:48.753-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T14:55:48.754-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:55:48.754-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T14:55:48.754-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:55:48.759-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-03-27T14:57:07.777-0500] {processor.py:186} INFO - Started process (PID=1786870) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:57:07.777-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T14:57:07.778-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:57:07.778-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:57:07.780-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:57:07.780-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T14:57:07.780-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:57:07.780-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T14:57:07.780-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:57:07.786-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-03-27T14:58:27.269-0500] {processor.py:186} INFO - Started process (PID=1787647) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:58:27.269-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T14:58:27.270-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:58:27.270-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:58:27.272-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:58:27.271-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T14:58:27.272-0500] {logging_mixin.py:190} INFO - [2025-03-27T14:58:27.272-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T14:58:27.272-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T14:58:27.277-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-03-27T15:00:02.388-0500] {processor.py:186} INFO - Started process (PID=1788676) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:00:02.389-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T15:00:02.390-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:00:02.390-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:00:02.393-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:00:02.393-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T15:00:02.393-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:00:02.393-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T15:00:02.393-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:00:02.399-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2025-03-27T15:01:08.781-0500] {processor.py:186} INFO - Started process (PID=1789465) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:01:08.781-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T15:01:08.782-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:01:08.782-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:01:08.785-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:01:08.784-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T15:01:08.785-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:01:08.785-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T15:01:08.785-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:01:08.790-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-03-27T15:02:13.028-0500] {processor.py:186} INFO - Started process (PID=1790209) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:02:13.029-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T15:02:13.030-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:02:13.029-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:02:13.031-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:02:13.031-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T15:02:13.031-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:02:13.031-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T15:02:13.032-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:02:13.037-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-03-27T15:03:30.896-0500] {processor.py:186} INFO - Started process (PID=1790950) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:03:30.896-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T15:03:30.897-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:03:30.897-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:03:30.899-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:03:30.898-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T15:03:30.899-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:03:30.899-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T15:03:30.899-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:03:30.904-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-03-27T15:04:43.774-0500] {processor.py:186} INFO - Started process (PID=1791779) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:04:43.775-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T15:04:43.775-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:04:43.775-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:04:43.779-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:04:43.778-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T15:04:43.779-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:04:43.779-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T15:04:43.779-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:04:43.784-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.013 seconds
[2025-03-27T15:06:05.155-0500] {processor.py:186} INFO - Started process (PID=1792487) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:06:05.156-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T15:06:05.157-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:06:05.157-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:06:05.159-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:06:05.158-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T15:06:05.159-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:06:05.159-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T15:06:05.159-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:06:05.164-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-03-27T15:07:32.464-0500] {processor.py:186} INFO - Started process (PID=1793373) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:07:32.465-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T15:07:32.466-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:07:32.465-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:07:32.467-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:07:32.467-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T15:07:32.467-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:07:32.467-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T15:07:32.468-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:07:32.473-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-03-27T15:08:36.226-0500] {processor.py:186} INFO - Started process (PID=1794018) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:08:36.227-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T15:08:36.228-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:08:36.227-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:08:36.229-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:08:36.229-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T15:08:36.229-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:08:36.229-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T15:08:36.229-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:08:36.235-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-03-27T15:09:43.890-0500] {processor.py:186} INFO - Started process (PID=1794748) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:09:43.890-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T15:09:43.891-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:09:43.891-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:09:43.893-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:09:43.892-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T15:09:43.893-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:09:43.893-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T15:09:43.893-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:09:43.898-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-03-27T15:10:54.341-0500] {processor.py:186} INFO - Started process (PID=1795424) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:10:54.341-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T15:10:54.342-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:10:54.342-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:10:54.344-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:10:54.343-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T15:10:54.344-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:10:54.344-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T15:10:54.344-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:10:54.349-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-03-27T15:12:00.726-0500] {processor.py:186} INFO - Started process (PID=1797621) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:12:00.726-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T15:12:00.727-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:12:00.727-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:12:00.729-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:12:00.729-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T15:12:00.729-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:12:00.729-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T15:12:00.729-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:12:00.734-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-03-27T15:13:20.805-0500] {processor.py:186} INFO - Started process (PID=1798356) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:13:20.805-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T15:13:20.806-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:13:20.806-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:13:20.808-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:13:20.808-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T15:13:20.808-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:13:20.808-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T15:13:20.808-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:13:20.814-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-03-27T15:14:36.691-0500] {processor.py:186} INFO - Started process (PID=1799154) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:14:36.691-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T15:14:36.692-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:14:36.692-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:14:36.694-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:14:36.694-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T15:14:36.694-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:14:36.694-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T15:14:36.694-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:14:36.700-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-03-27T15:15:53.839-0500] {processor.py:186} INFO - Started process (PID=1799976) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:15:53.840-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T15:15:53.841-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:15:53.840-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:15:53.842-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:15:53.842-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T15:15:53.842-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:15:53.842-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T15:15:53.843-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:15:53.848-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-03-27T15:17:12.802-0500] {processor.py:186} INFO - Started process (PID=1800682) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:17:12.802-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T15:17:12.803-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:17:12.803-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:17:12.805-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:17:12.804-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T15:17:12.805-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:17:12.805-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T15:17:12.805-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:17:12.810-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-03-27T15:18:20.174-0500] {processor.py:186} INFO - Started process (PID=1801345) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:18:20.175-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T15:18:20.176-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:18:20.176-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:18:20.178-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:18:20.177-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T15:18:20.178-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:18:20.178-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T15:18:20.178-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:18:20.183-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-03-27T15:19:29.973-0500] {processor.py:186} INFO - Started process (PID=1802032) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:19:29.974-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T15:19:29.975-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:19:29.975-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:19:29.976-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:19:29.976-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T15:19:29.977-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:19:29.977-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T15:19:29.977-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:19:29.982-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-03-27T15:20:36.239-0500] {processor.py:186} INFO - Started process (PID=1803479) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:20:36.239-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T15:20:36.240-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:20:36.240-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:20:36.242-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:20:36.241-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T15:20:36.242-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:20:36.242-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T15:20:36.242-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:20:36.247-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-03-27T15:21:46.832-0500] {processor.py:186} INFO - Started process (PID=1808335) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:21:46.832-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T15:21:46.833-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:21:46.833-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:21:46.835-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:21:46.835-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T15:21:46.835-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:21:46.835-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T15:21:46.835-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:21:46.841-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-03-27T15:23:05.259-0500] {processor.py:186} INFO - Started process (PID=1809057) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:23:05.259-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T15:23:05.260-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:23:05.260-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:23:05.262-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:23:05.262-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T15:23:05.262-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:23:05.262-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T15:23:05.262-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:23:05.267-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-03-27T15:24:13.926-0500] {processor.py:186} INFO - Started process (PID=1809814) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:24:13.926-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T15:24:13.927-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:24:13.927-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:24:13.929-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:24:13.929-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T15:24:13.929-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:24:13.929-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T15:24:13.930-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:24:13.935-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-03-27T15:25:33.222-0500] {processor.py:186} INFO - Started process (PID=1810605) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:25:33.223-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T15:25:33.224-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:25:33.224-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:25:33.226-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:25:33.226-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T15:25:33.226-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:25:33.226-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T15:25:33.226-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:25:33.232-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-03-27T15:27:08.108-0500] {processor.py:186} INFO - Started process (PID=1811515) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:27:08.108-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T15:27:08.109-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:27:08.109-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:27:08.111-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:27:08.110-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T15:27:08.111-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:27:08.111-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T15:27:08.111-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:27:08.116-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-03-27T15:28:24.190-0500] {processor.py:186} INFO - Started process (PID=1812207) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:28:24.190-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T15:28:24.191-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:28:24.191-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:28:24.193-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:28:24.192-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T15:28:24.193-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:28:24.193-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T15:28:24.193-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:28:24.198-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-03-27T15:30:12.320-0500] {processor.py:186} INFO - Started process (PID=1813249) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:30:12.320-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T15:30:12.321-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:30:12.321-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:30:12.323-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:30:12.322-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T15:30:12.323-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:30:12.323-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T15:30:12.323-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:30:12.328-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-03-27T15:32:02.848-0500] {processor.py:186} INFO - Started process (PID=1814319) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:32:02.849-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T15:32:02.850-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:32:02.850-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:32:02.851-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:32:02.851-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T15:32:02.852-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:32:02.852-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T15:32:02.852-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:32:02.857-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-03-27T15:33:14.595-0500] {processor.py:186} INFO - Started process (PID=1814942) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:33:14.596-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T15:33:14.597-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:33:14.597-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:33:14.598-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:33:14.598-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T15:33:14.599-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:33:14.599-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T15:33:14.599-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:33:14.604-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
[2025-03-27T15:34:20.788-0500] {processor.py:186} INFO - Started process (PID=1815604) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:34:20.788-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T15:34:20.789-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:34:20.789-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:34:20.791-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:34:20.790-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T15:34:20.791-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:34:20.791-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T15:34:20.791-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:34:20.796-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.012 seconds
[2025-03-27T15:35:27.403-0500] {processor.py:186} INFO - Started process (PID=1816264) to work on /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:35:27.403-0500] {processor.py:914} INFO - Processing file /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-27T15:35:27.404-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:35:27.404-0500] {dagbag.py:588} INFO - Filling up the DagBag from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:35:27.406-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:35:27.405-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-27T15:35:27.406-0500] {logging_mixin.py:190} INFO - [2025-03-27T15:35:27.406-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-27T15:35:27.406-0500] {processor.py:927} WARNING - No viable dags retrieved from /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-27T15:35:27.411-0500] {processor.py:208} INFO - Processing /home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.011 seconds
