[2025-04-03T16:37:51.264-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-03T16:37:51.269-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xcom.A scheduled__2025-04-02T00:00:00+00:00 [queued]>
[2025-04-03T16:37:51.272-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xcom.A scheduled__2025-04-02T00:00:00+00:00 [queued]>
[2025-04-03T16:37:51.272-0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-03T16:37:51.408-0500] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): A> on 2025-04-02 00:00:00+00:00
[2025-04-03T16:37:51.410-0500] {standard_task_runner.py:72} INFO - Started process 1638498 to run task
[2025-04-03T16:37:51.411-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'xcom', 'A', 'scheduled__2025-04-02T00:00:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/xcom.py', '--cfg-path', '/tmp/tmp2u_q5por']
[2025-04-03T16:37:51.412-0500] {standard_task_runner.py:105} INFO - Job 55: Subtask A
[2025-04-03T16:37:51.571-0500] {task_command.py:467} INFO - Running <TaskInstance: xcom.A scheduled__2025-04-02T00:00:00+00:00 [running]> on host royal-07.cs.wisc.edu
[2025-04-03T16:37:51.861-0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cloud.user' AIRFLOW_CTX_DAG_ID='xcom' AIRFLOW_CTX_TASK_ID='A' AIRFLOW_CTX_EXECUTION_DATE='2025-04-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-02T00:00:00+00:00'
[2025-04-03T16:37:51.861-0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-03T16:37:51.931-0500] {logging_mixin.py:190} INFO - Count 100
[2025-04-03T16:37:51.931-0500] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/airflow/dags/xcom.py", line 13, in inc
    return ctr1 + 1
           ^^^^
NameError: name 'ctr1' is not defined
[2025-04-03T16:37:52.007-0500] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=xcom, task_id=A, run_id=scheduled__2025-04-02T00:00:00+00:00, execution_date=20250402T000000, start_date=20250403T213751, end_date=20250403T213752
[2025-04-03T16:37:53.386-0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-03T16:37:53.387-0500] {standard_task_runner.py:124} ERROR - Failed to execute job 55 for task A (name 'ctr1' is not defined; 1638498)
Traceback (most recent call last):
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/miniconda3/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/udhbhav/airflow/dags/xcom.py", line 13, in inc
    return ctr1 + 1
           ^^^^
NameError: name 'ctr1' is not defined
[2025-04-03T16:37:53.472-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-03T16:37:53.481-0500] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-03T16:37:53.610-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
