[2025-03-28T16:27:59.493-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-28T16:27:59.498-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hw.task_hw scheduled__2025-03-27T00:00:00+00:00 [queued]>
[2025-03-28T16:27:59.500-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hw.task_hw scheduled__2025-03-27T00:00:00+00:00 [queued]>
[2025-03-28T16:27:59.500-0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-28T16:27:59.701-0500] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task_hw> on 2025-03-27 00:00:00+00:00
[2025-03-28T16:27:59.703-0500] {standard_task_runner.py:72} INFO - Started process 2948966 to run task
[2025-03-28T16:27:59.705-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'hw', 'task_hw', 'scheduled__2025-03-27T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/hello_world.py', '--cfg-path', '/tmp/tmp87oammd4']
[2025-03-28T16:27:59.706-0500] {standard_task_runner.py:105} INFO - Job 20: Subtask task_hw
[2025-03-28T16:27:59.852-0500] {task_command.py:467} INFO - Running <TaskInstance: hw.task_hw scheduled__2025-03-27T00:00:00+00:00 [running]> on host royal-07.cs.wisc.edu
[2025-03-28T16:28:00.172-0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cloud.user' AIRFLOW_CTX_DAG_ID='hw' AIRFLOW_CTX_TASK_ID='task_hw' AIRFLOW_CTX_EXECUTION_DATE='2025-03-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-27T00:00:00+00:00'
[2025-03-28T16:28:00.172-0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-28T16:28:00.179-0500] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-28T16:28:00.179-0500] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Hello World Again"']
[2025-03-28T16:28:00.183-0500] {subprocess.py:99} INFO - Output:
[2025-03-28T16:28:00.183-0500] {subprocess.py:106} INFO - Hello World Again
[2025-03-28T16:28:00.183-0500] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-28T16:28:00.295-0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-28T16:28:00.295-0500] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=hw, task_id=task_hw, run_id=scheduled__2025-03-27T00:00:00+00:00, execution_date=20250327T000000, start_date=20250328T212759, end_date=20250328T212800
[2025-03-28T16:28:00.599-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-28T16:28:00.604-0500] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-28T16:28:00.605-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
