[2025-03-28T16:29:11.253-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-28T16:29:11.257-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hw.task_hw manual__2025-03-28T21:29:08.601155+00:00 [queued]>
[2025-03-28T16:29:11.260-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hw.task_hw manual__2025-03-28T21:29:08.601155+00:00 [queued]>
[2025-03-28T16:29:11.260-0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-28T16:29:11.399-0500] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task_hw> on 2025-03-28 21:29:08.601155+00:00
[2025-03-28T16:29:11.401-0500] {standard_task_runner.py:72} INFO - Started process 2949523 to run task
[2025-03-28T16:29:11.402-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'hw', 'task_hw', 'manual__2025-03-28T21:29:08.601155+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/hello_world.py', '--cfg-path', '/tmp/tmp3bu8fifb']
[2025-03-28T16:29:11.403-0500] {standard_task_runner.py:105} INFO - Job 21: Subtask task_hw
[2025-03-28T16:29:11.544-0500] {task_command.py:467} INFO - Running <TaskInstance: hw.task_hw manual__2025-03-28T21:29:08.601155+00:00 [running]> on host royal-07.cs.wisc.edu
[2025-03-28T16:29:11.797-0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cloud.user' AIRFLOW_CTX_DAG_ID='hw' AIRFLOW_CTX_TASK_ID='task_hw' AIRFLOW_CTX_EXECUTION_DATE='2025-03-28T21:29:08.601155+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-28T21:29:08.601155+00:00'
[2025-03-28T16:29:11.797-0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-28T16:29:11.805-0500] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-28T16:29:11.805-0500] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Hello World Again"']
[2025-03-28T16:29:11.809-0500] {subprocess.py:99} INFO - Output:
[2025-03-28T16:29:11.809-0500] {subprocess.py:106} INFO - Hello World Again
[2025-03-28T16:29:11.810-0500] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-28T16:29:12.148-0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-28T16:29:12.148-0500] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=hw, task_id=task_hw, run_id=manual__2025-03-28T21:29:08.601155+00:00, execution_date=20250328T212908, start_date=20250328T212911, end_date=20250328T212912
[2025-03-28T16:29:12.417-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-28T16:29:12.423-0500] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-28T16:29:12.423-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
