[2025-03-31T13:01:09.545-0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-31T13:01:09.551-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: exec_mult_tasks.2 manual__2025-03-31T18:01:01.116987+00:00 [queued]>
[2025-03-31T13:01:09.554-0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: exec_mult_tasks.2 manual__2025-03-31T18:01:01.116987+00:00 [queued]>
[2025-03-31T13:01:09.554-0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-31T13:01:09.693-0500] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): 2> on 2025-03-31 18:01:01.116987+00:00
[2025-03-31T13:01:09.694-0500] {standard_task_runner.py:72} INFO - Started process 414145 to run task
[2025-03-31T13:01:09.696-0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'exec_mult_tasks', '2', 'manual__2025-03-31T18:01:01.116987+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/exec_multiple_tasks.py', '--cfg-path', '/tmp/tmpx5xdpvjn']
[2025-03-31T13:01:09.697-0500] {standard_task_runner.py:105} INFO - Job 34: Subtask 2
[2025-03-31T13:01:10.201-0500] {task_command.py:467} INFO - Running <TaskInstance: exec_mult_tasks.2 manual__2025-03-31T18:01:01.116987+00:00 [running]> on host royal-07.cs.wisc.edu
[2025-03-31T13:01:10.487-0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cloud.user' AIRFLOW_CTX_DAG_ID='exec_mult_tasks' AIRFLOW_CTX_TASK_ID='2' AIRFLOW_CTX_EXECUTION_DATE='2025-03-31T18:01:01.116987+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-31T18:01:01.116987+00:00'
[2025-03-31T13:01:10.487-0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-31T13:01:10.496-0500] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-31T13:01:10.496-0500] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "Task 2 executed"']
[2025-03-31T13:01:10.499-0500] {subprocess.py:99} INFO - Output:
[2025-03-31T13:01:10.499-0500] {subprocess.py:106} INFO - Task 2 executed
[2025-03-31T13:01:10.500-0500] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-31T13:01:10.608-0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-31T13:01:10.608-0500] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=exec_mult_tasks, task_id=2, run_id=manual__2025-03-31T18:01:01.116987+00:00, execution_date=20250331T180101, start_date=20250331T180109, end_date=20250331T180110
[2025-03-31T13:01:10.952-0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-31T13:01:10.960-0500] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-31T13:01:10.960-0500] {local_task_job_runner.py:245} INFO - ::endgroup::
